functions:
  tzapi:
    runtime: go
    desc: ""
    maintainer: ""
    handler:
      dir: ./src
      file: ""
      name: Handler
    docker_registry: 10.0.1.150:5000/cyy
    image: 10.0.1.150:5000/cyy/tzapi
    constraints:
    - nodetype=cpunode
    limits:
      memory: ""
      cpu: ""
      gpu: ""
    requests:
      memory: 50Mi
      cpu: 50m
      gpu: ""
faas:
  gateway: 10.0.2.103:31113
