apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: pcc
  labels:
    app: minio
spec:
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 32171
  selector:
    app: minio
