apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: pcc
  labels:
    app: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 32170
  selector:
    app: minio
