apiVersion: v1
kind: Service
metadata:
  name: console-svc
  namespace: minio-operator
  labels:
    app: console
spec:
  type: NodePort
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 32170
  selector:
    app: console
