apiVersion: apps/v1
kind: Deployment
metadata:
  name: fxgateway
  namespace: kubesphere-faas-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fxgateway
  template:
    metadata:
      labels:
        app: fxgateway
    spec:
      serviceAccountName: fxgateway
      imagePullSecrets:
        - name: regcred
      containers:
      - name: fxgateway
        image: 10.0.1.150:5000/2021_hv/fxgateway:3.0
        imagePullPolicy: Always
        env:
        - name: FUNCTION_NAMESPACE
          value: kubesphere-faas-fn
        - name: VM_NAMESPACE
          value: kubesphere-faas-vm
        - name: IMAGE_PULL_POLICY
          value: "Always"

        ports:
        - containerPort: 10000
          protocol: TCP

        resources:
          requests:
            memory: 250Mi
          limits:
            memory: 250Mi
